version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nexus-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nexuspassword2026
      POSTGRES_DB: nexus_erp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
